### PR TITLE
Fix for HA 0.110.0b

### PR DESCRIPTION
**Pull request by noxhirsch**
Change all paper-icon-button to ha-icon-button which fixes Custom Header in HA 0.110.0b 
https://github.com/maykar/custom-header/issues/179

### CODE REVIEW

**Comment by maykar** [comment]
Thanks for this, when I get a chance I need to update it to be backwards compatible before I pull. Should be easy enough just need to change all query selectors to something like:

 `element.querySelector('paper-icon-button') || element.querySelector('ha-icon-button')`

**Comment by noxhirsch** [comment]
Damn... I forgot about backwards compatibility. 
I added the selector for paper-icon-button on some places, but not everywhere, because I don't really know JS and don't want to mess up your code - sorry!

**Comment by maykar** [comment]
No worries at all, really appreciate the help. I'll try to test this later tonight and get it pulled.

**Comment by olivierjag2** [comment]
> Change all paper-icon-button to ha-icon-button which fixes Custom Header in HA 0.110.0b 
> 
> https://github.com/maykar/custom-header/issues/179 

Hi I have 0.110.0b2 and I have the same problem, thx

**Comment by Stretcherfetcher** [comment]
Don't know if this is the same problem but no custom header visible in 0.110.0b2 Had to uninstall it to get default header back.

Log Details (ERROR)
Logger: frontend.js.latest.202005141
Source: components/system_log/__init__.py:209
First occurred: 13:11:13 (1 occurrences)
Last logged: 13:11:13

http://X.X.X.X:8123/hacsfiles/custom-header/custom-header.js:1:16344 Uncaught TypeError: Cannot read property 'style' of null

**Comment by DavidFW1960** [comment]
> Change all paper-icon-button to ha-icon-button which fixes Custom Header in HA 0.110.0b

Tried that and it 99% fixes custom_header but clicking on the hamburger menu to bring up the side panel doesn't work.

**Comment by maykar** [comment]
I'm working on it, there's a bit more to it than just the icon element changes. Hoping to get 0.110 fixes as well as a handful of other things in this week.

**Comment by bramkragten** [comment]
> `element.querySelector('paper-icon-button') || element.querySelector('ha-icon-button')`

`element.querySelector('ha-icon-button, paper-icon-button')`

**Comment by user897943** [comment]
If this fix has been released then it's not showing on HACS yet...

**Comment by maykar** [comment]
This has not been released see info below this comment.

**Pull request merged**
